# frozen_string_literal: true

# Copyright The OpenTelemetry Authors
#
# SPDX-License-Identifier: Apache-2.0

source 'https://rubygems.org'

gemspec

gem 'opentelemetry-instrumentation-action_cable', path: '../action_cable'
gem 'opentelemetry-instrumentation-racecar', path: '../racecar'
gem 'opentelemetry-instrumentation-rake', path: '../rake'
